Repository AiursoftWeb/Kahla.CLI, pull requests merged in 2019-04, with the labels that each got.

#9 fix #8
  Library/processmessage.py
Labels: bug, invalid

#10 Fix Some Missing Bugs
  Library/processmessage.py
Labels: bug, invalid

#15 fix #14
  Controllers/DeleteFriendsController.py
  Controllers/FriendsController.py
  Controllers/GetMessagesController.py
  Controllers/GroupsController.py
  Controllers/LeaveGroupsController.py
  Controllers/ListenController.py
  Controllers/LoginController.py
  Controllers/LogoutController.py
  Controllers/SearchFriendsController.py
  Controllers/SearchGroupsController.py
  Controllers/SendController.py
  Controllers/UseMasterController.py
  Controllers/UseStaggingController.py
  Library/Controller.py
  Library/cryptojs.py
  Services/KahlaApiAddressService.py
  Services/KahlaAuthApiService.py
  Services/KahlaFriendShipApiService.py
  Services/KahlaSignInStatusCheckService.py
  Services/StorageCookieService.py
  Startup.py
  Views/FriendsView.py
  Views/GroupsView.py
  Views/LoginView.py
  Views/LogoutView.py
  Views/SearchFriendsView.py
  Views/UseMasterView.py
  Views/UseStaggingView.py
Labels: bug

#16 fix #12
  Controllers/GetMessagesController.py
Labels: bug, invalid

#19 fix#18
  Checks/DeleteFriendsChecker.py
  Checks/LoginChecker.py
Labels: bug, invalid

#20 fix#13
  Checks/GetMessagesChecker.py
  Checks/LeaveGroupsChecker.py
  Checks/LoginChecker.py
  Checks/SearchFriendsChecker.py
  Checks/SearchGroupsChecker.py
  Checks/SendChecker.py
  Controllers/GetMessagesController.py
  Controllers/SearchFriendsController.py
  Controllers/SearchGroupsController.py
  Controllers/SendController.py
Labels: bug, invalid

#22 fix#21
  Controllers/FriendsController.py
  Controllers/GetMessagesController.py
  Controllers/GroupsController.py
  Controllers/LeaveGroupsController.py
  Controllers/LogoutController.py
  Controllers/SearchFriendsController.py
  Controllers/SearchGroupsController.py
  Listener/KahlaWebSocketListener.py
  Services/KahlaAuthApiService.py
  Services/KahlaConversationApiService.py
  Services/KahlaFileApiService.py
  Services/KahlaFriendShipApiService.py
  Services/KahlaGroupApiService.py
Labels: invalid

#24 fix#23
  publishforlinux.sh
Labels: bug, invalid

#26 fix#25
  README.md
Labels: invalid
